name: Currency Alert

on:
  schedule:
    # every day at 10:15 AM UTC (03:15 AM PT, 05:15 AM CT, 06:15 AM ET)
    - cron: "15 10 * * *"

  workflow_dispatch:
    inputs:
      source_currency:
        description: "Source currency"
        required: false
        default: "USD"
      target_currency:
        description: "Target currency"
        required: false
        default: "INR"
      email:
        description: "Alert email address"
        required: true

jobs:
  currency-alert:
    runs-on: ubuntu-latest
    environment: "currency"
    env:
      EXCHANGE_RATE_API_KEY: ${{ secrets.EXCHANGE_RATE_API_KEY }}
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
      GOOGLE_APP_PASSWORD: ${{ secrets.GOOGLE_APP_PASSWORD }}
      OPENEXCHANGERATES_APP_ID: ${{ secrets.OPENEXCHANGERATES_APP_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Determine inputs
        id: inputs
        run: |
          echo "source_currency=${{ github.event.inputs.source_currency || 'USD' }}" >> $GITHUB_OUTPUT
          echo "target_currency=${{ github.event.inputs.target_currency || 'INR' }}" >> $GITHUB_OUTPUT
          echo "email=${{ github.event.inputs.email || secrets.ALERT_EMAIL }}" >> $GITHUB_OUTPUT

      - name: Run currency alert
        run: |
          echo "Converting ${{ steps.inputs.outputs.source_currency }} to ${{ steps.inputs.outputs.target_currency }}."
          python main.py currency \
            -s "${{ steps.inputs.outputs.source_currency }}" \
            -t "${{ steps.inputs.outputs.target_currency }}" \
            -e "${{ steps.inputs.outputs.email }}"
